[window]
startup_mode = "Maximized"
padding = {x = 5, y = 10}
decorations = 'Buttonless'

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 15

[general]
import = [
	"gruvbox_material_hard_dark.toml",
]
